"""added esports team id to metadata

Revision ID: 13be3af2fa5b
Revises: 7d0a0b80d5bc
Create Date: 2020-01-28 22:00:38.101634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13be3af2fa5b'
down_revision = '7d0a0b80d5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_player_metadata', sa.Column('esports_team_id', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_player_metadata', 'esports_team_id')
    # ### end Alembic commands ###
