"""Updated some ints to bigints

Revision ID: 7d0a0b80d5bc
Revises: a259288446da
Create Date: 2020-01-28 21:54:30.875355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0a0b80d5bc'
down_revision = 'a259288446da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_frames', 'game_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('game_player_metadata', 'esports_player_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('game_player_metadata', 'game_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT())
    op.alter_column('game_player_metadata', 'match_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('games', 'game_id',
               existing_type=sa.INTEGER(),
               type_=sa.BIGINT(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('games_game_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'game_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               autoincrement=True,
               existing_server_default=sa.text("nextval('games_game_id_seq'::regclass)"))
    op.alter_column('game_player_metadata', 'match_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('game_player_metadata', 'game_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER())
    op.alter_column('game_player_metadata', 'esports_player_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('game_frames', 'game_id',
               existing_type=sa.BIGINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
