"""Removed unnecisary ID from the metadata thing

Revision ID: 913a7c94a17a
Revises: 13be3af2fa5b
Create Date: 2020-02-11 10:59:32.676439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913a7c94a17a'
down_revision = '13be3af2fa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_player_metadata', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_player_metadata', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
