"""rune name field was too short

Revision ID: 942a338729c5
Revises: 7d9515d301c7
Create Date: 2020-02-11 11:24:27.476450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942a338729c5'
down_revision = '7d9515d301c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runes_lookup', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runes_lookup', 'name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
